# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Government Services Collective
email: lauren.f.lockwood@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Empowering government to do more good in a digital age.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Team names, titles and social links
people:

- name: Lauren Lockwood
  pic: LL
  position: Co-founder & Director
  social:
    - title: twitter
      url: https://twitter.com/lflockwood
    - title: linkedin
      url: https://www.linkedin.com/in/lflockwood
    - title: medium
      url: https://medium.com/@lflockwood

- name: Aaron Ogle
  pic: AO
  position: Director of Product, Open Gov Foundation
  social:
    - title: twitter
      url: https://twitter.com/atogle
    - title: linkedin
      url: https://www.linkedin.com/in/atogle

- name: Aaron Snow
  pic: AS
  position: Co-founder & Advisor
  social:
    - title: twitter
      url: https://twitter.com/aaronsnow
    - title: linkedin
      url: https://www.linkedin.com/in/aaronsnow
    - title: medium
      url: https://medium.com/@aaronsnow


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/lflockwood
  - title: github
    url: http://github.com/lflockwood

# Postal address (add as many lines as necessary)
address:
  - line: 123 Main St.
  - line: Philadelphia, PA 19072

# Build settings
markdown: kramdown
theme: agency-jekyll-theme
plugins:
  - jekyll-feed



# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
